spring:
  datasource:
    url: jdbc:h2:mem:~/todo
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
